[2025-02-01T02:00:20.958+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:00:15.984417+00:00 [queued]>
[2025-02-01T02:00:20.963+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:00:15.984417+00:00 [queued]>
[2025-02-01T02:00:20.964+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T02:00:20.972+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_bigquery> on 2025-02-01 02:00:15.984417+00:00
[2025-02-01T02:00:20.976+0000] {standard_task_runner.py:57} INFO - Started process 1263 to run task
[2025-02-01T02:00:20.978+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bigquery_dag', 'upload_to_bigquery', 'manual__2025-02-01T02:00:15.984417+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/json_to_bigquery.py', '--cfg-path', '/tmp/tmpdpz44ymv']
[2025-02-01T02:00:20.980+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask upload_to_bigquery
[2025-02-01T02:00:21.010+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:00:15.984417+00:00 [running]> on host 3f33197bb456
[2025-02-01T02:00:21.062+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='upload_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T02:00:15.984417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T02:00:15.984417+00:00'
[2025-02-01T02:00:21.068+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T02:00:21.076+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_to_bigquery.py", line 104, in upload_to_bigquery
    "arrival_airport", "departure_time", "arrival_time", "carbon_emission"]
TypeError: insert_rows() missing 1 required positional argument: 'table'
[2025-02-01T02:00:21.082+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bigquery_dag, task_id=upload_to_bigquery, execution_date=20250201T020015, start_date=20250201T020020, end_date=20250201T020021
[2025-02-01T02:00:21.087+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 110 for task upload_to_bigquery (insert_rows() missing 1 required positional argument: 'table'; 1263)
[2025-02-01T02:00:21.118+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T02:00:21.130+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
