[2025-02-01T00:58:53.036+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:53:34.591510+00:00 [queued]>
[2025-02-01T00:58:53.062+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:53:34.591510+00:00 [queued]>
[2025-02-01T00:58:53.062+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-02-01T00:58:53.078+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_ndjson_to_bigquery> on 2025-02-01 00:53:34.591510+00:00
[2025-02-01T00:58:53.089+0000] {standard_task_runner.py:57} INFO - Started process 2147 to run task
[2025-02-01T00:58:53.115+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_gcs_to_bigquery', 'load_ndjson_to_bigquery', 'manual__2025-02-01T00:53:34.591510+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_test_dag.py', '--cfg-path', '/tmp/tmpmhsdl7o4']
[2025-02-01T00:58:53.118+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask load_ndjson_to_bigquery
[2025-02-01T00:58:53.158+0000] {task_command.py:410} INFO - Running <TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:53:34.591510+00:00 [running]> on host 3f33197bb456
[2025-02-01T00:58:53.349+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='load_ndjson_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:53:34.591510+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:53:34.591510+00:00'
[2025-02-01T00:58:53.412+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T00:58:54.013+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:1717 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2025-02-01T00:58:54.022+0000] {bigquery.py:1592} INFO - Inserting job ***_1738371534019265_d427d839252f6088b0183d444aa84c25
[2025-02-01T00:58:54.967+0000] {logging_mixin.py:150} INFO - [ERROR] BigQuery 로드 실패: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. File: gs://ticket_checker_bucket/naver_flight_data/flight_results_ndjson.json
[2025-02-01T00:58:54.968+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-01T00:58:55.002+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=test_gcs_to_bigquery, task_id=load_ndjson_to_bigquery, execution_date=20250201T005334, start_date=20250201T005853, end_date=20250201T005855
[2025-02-01T00:58:55.066+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-02-01T00:58:55.100+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
