[2025-02-01T01:15:15.305+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:15:10.214853+00:00 [queued]>
[2025-02-01T01:15:15.310+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:15:10.214853+00:00 [queued]>
[2025-02-01T01:15:15.310+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T01:15:15.317+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_ndjson_to_bigquery> on 2025-02-01 01:15:10.214853+00:00
[2025-02-01T01:15:15.322+0000] {standard_task_runner.py:57} INFO - Started process 2809 to run task
[2025-02-01T01:15:15.325+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_gcs_to_bigquery', 'load_ndjson_to_bigquery', 'manual__2025-02-01T01:15:10.214853+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_test_dag.py', '--cfg-path', '/tmp/tmpfjdo1qs7']
[2025-02-01T01:15:15.328+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask load_ndjson_to_bigquery
[2025-02-01T01:15:15.385+0000] {task_command.py:410} INFO - Running <TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:15:10.214853+00:00 [running]> on host 3f33197bb456
[2025-02-01T01:15:15.473+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='load_ndjson_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T01:15:10.214853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T01:15:10.214853+00:00'
[2025-02-01T01:15:15.480+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:15:15.489+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:15:15.977+0000] {logging_mixin.py:150} INFO - [ERROR] JSON 파싱 오류: Extra data: line 2 column 1 (char 171)
[2025-02-01T01:15:15.978+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-01T01:15:16.001+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=test_gcs_to_bigquery, task_id=load_ndjson_to_bigquery, execution_date=20250201T011510, start_date=20250201T011515, end_date=20250201T011516
[2025-02-01T01:15:16.062+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-02-01T01:15:16.087+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
