[2025-02-01T01:44:59.050+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver_flight_bigquery_pipeline.process_flight_data manual__2025-02-01T01:39:49.402109+00:00 [queued]>
[2025-02-01T01:44:59.055+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver_flight_bigquery_pipeline.process_flight_data manual__2025-02-01T01:39:49.402109+00:00 [queued]>
[2025-02-01T01:44:59.058+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-02-01T01:44:59.067+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_flight_data> on 2025-02-01 01:39:49.402109+00:00
[2025-02-01T01:44:59.071+0000] {standard_task_runner.py:57} INFO - Started process 746 to run task
[2025-02-01T01:44:59.074+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'naver_flight_bigquery_pipeline', 'process_flight_data', 'manual__2025-02-01T01:39:49.402109+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/json_to_bigquery.py', '--cfg-path', '/tmp/tmp3clikqed']
[2025-02-01T01:44:59.077+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask process_flight_data
[2025-02-01T01:44:59.118+0000] {task_command.py:410} INFO - Running <TaskInstance: naver_flight_bigquery_pipeline.process_flight_data manual__2025-02-01T01:39:49.402109+00:00 [running]> on host 3f33197bb456
[2025-02-01T01:44:59.167+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='naver_flight_bigquery_pipeline' AIRFLOW_CTX_TASK_ID='process_flight_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T01:39:49.402109+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T01:39:49.402109+00:00'
[2025-02-01T01:44:59.172+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:45:00.986+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:45:00.989+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_to_bigquery.py", line 91, in upload_to_bigquery
    hook_bq.insert_rows(table=table_ref, rows=df.to_dict(orient='records'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 236, in insert_rows
    raise NotImplementedError()
NotImplementedError
[2025-02-01T01:45:00.996+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=naver_flight_bigquery_pipeline, task_id=process_flight_data, execution_date=20250201T013949, start_date=20250201T014459, end_date=20250201T014500
[2025-02-01T01:45:01.006+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 107 for task process_flight_data (; 746)
[2025-02-01T01:45:01.043+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T01:45:01.069+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
