[2025-02-01T01:03:06.494+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:02:56.990323+00:00 [queued]>
[2025-02-01T01:03:06.505+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:02:56.990323+00:00 [queued]>
[2025-02-01T01:03:06.506+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T01:03:06.518+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_ndjson_to_bigquery> on 2025-02-01 01:02:56.990323+00:00
[2025-02-01T01:03:06.522+0000] {standard_task_runner.py:57} INFO - Started process 2332 to run task
[2025-02-01T01:03:06.525+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_gcs_to_bigquery', 'load_ndjson_to_bigquery', 'manual__2025-02-01T01:02:56.990323+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_test_dag.py', '--cfg-path', '/tmp/tmpe09dv1_2']
[2025-02-01T01:03:06.527+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask load_ndjson_to_bigquery
[2025-02-01T01:03:06.561+0000] {task_command.py:410} INFO - Running <TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T01:02:56.990323+00:00 [running]> on host 3f33197bb456
[2025-02-01T01:03:06.619+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='load_ndjson_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T01:02:56.990323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T01:02:56.990323+00:00'
[2025-02-01T01:03:06.625+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:03:06.630+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:03:10.837+0000] {logging_mixin.py:150} INFO - [ERROR] JSON 파싱 오류: Extra data: line 2 column 1 (char 1353)
[2025-02-01T01:03:10.842+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-01T01:03:10.905+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=test_gcs_to_bigquery, task_id=load_ndjson_to_bigquery, execution_date=20250201T010256, start_date=20250201T010306, end_date=20250201T010310
[2025-02-01T01:03:10.967+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-02-01T01:03:11.000+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
